import type { HeroArchetype } from "@/lib/types";

// Fill in each hero's archetype: "dive" | "brawl" | "poke".
// The seed fails if any hero is left as null.
export const ARCHETYPES: Record<string, HeroArchetype | null> = {
  "ana": "poke",
  "anran": "dive",
  "ashe": "poke",
  "baptiste": "poke",
  "bastion": "brawl",
  "brigitte": "brawl",
  "cassidy": "brawl",
  "dmon": "dive",
  "domina": "poke",
  "doomfist": "dive",
  "dva": "dive",
  "echo": "dive",
  "emre": "poke",
  "freja": "poke",
  "genji": "dive",
  "hanzo": "poke",
  "hazard": "brawl",
  "illari": "brawl",
  "jetpack-cat": "dive",
  "junker-queen": "brawl",
  "junkrat": "brawl",
  "juno": "poke",
  "kiriko": "dive",
  "lifeweaver": "poke",
  "lucio": "dive",
  "mauga": "brawl",
  "mei": "brawl",
  "mercy": "dive",
  "mizuki": "dive",
  "moira": "brawl",
  "orisa": "poke",
  "pharah": "dive",
  "ramattra": "brawl",
  "reaper": "brawl",
  "reinhardt": "brawl",
  "roadhog": "brawl",
  "shion": "dive",
  "sierra": "poke",
  "sigma": "poke",
  "sojourn": "poke",
  "soldier-76": "poke",
  "sombra": "dive",
  "symmetra": "brawl",
  "torbjorn": "poke",
  "tracer": "dive",
  "vendetta": "dive",
  "venture": "dive",
  "widowmaker": "poke",
  "winston": "dive",
  "wrecking-ball": "dive",
  "wuyang": "dive",
  "zarya": "brawl",
  "zenyatta": "poke",
};
